"""Add is_active to User table

Revision ID: 3f63016c1287
Revises: 80893c4f21f2
Create Date: 2024-11-28 21:51:01.330147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f63016c1287'
down_revision: Union[str, None] = '80893c4f21f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), default=False, nullable=True))
    # ### end Alembic commands ###
    # Fill values for existing data
    op.execute("UPDATE users SET is_active = True WHERE is_active IS NULL")
    # Set is_active NOT NULL
    op.alter_column('users', 'is_active', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
