"""Init

Revision ID: be3614e90370
Revises: 
Create Date: 2024-11-15 11:45:58.276563

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be3614e90370"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("additional_info", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contact_email"), "contact", ["email"], unique=True)
    op.create_index(
        op.f("ix_contact_first_name"), "contact", ["first_name"], unique=False
    )
    op.create_index(op.f("ix_contact_id"), "contact", ["id"], unique=False)
    op.create_index(
        op.f("ix_contact_last_name"), "contact", ["last_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contact_last_name"), table_name="contact")
    op.drop_index(op.f("ix_contact_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_first_name"), table_name="contact")
    op.drop_index(op.f("ix_contact_email"), table_name="contact")
    op.drop_table("contact")
    # ### end Alembic commands ###
