"""add avatar field to user table

Revision ID: d0a757351d70
Revises: 3f63016c1287
Create Date: 2024-11-30 11:37:26.194873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0a757351d70"
down_revision: Union[str, None] = "3f63016c1287"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar", sa.String(length=250), nullable=True))
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
